### ISSUE TITLE
Friday Fanart page update (#65-#152)

### ISSUE THREAD

**Issue by Infimix2024** [botworld-wiki/beatburger.github.io#29]
![#65 D16 M12 Y2022 W-Marykains.jpg](https://github.com/user-attachments/assets/88fc83a6-cb31-4dc5-a0ba-e85aa1895d41)

![#66 D-23 M-12 Y-2022 W-@HostyTosty.jpg](https://github.com/user-attachments/assets/bb60f2d7-1a34-4164-94d0-f76cffc5c8c9)

![#67 D-30 M-12 Y-2022 W-Lavasauros.jpg](https://github.com/user-attachments/assets/52bc2006-37b1-4519-9583-025bbdfe84b0)

![#68 D-6 M-1 Y-2023 W-@HostyTosty.jpg](https://github.com/user-attachments/assets/f4fe31b4-b35e-4bec-ae8a-1eb13293e4e0)

![#69 D-13 M-1 Y-2023 W-Foxxive.jpg](https://github.com/user-attachments/assets/c9efda33-490e-41f9-9965-447f9bbe8dda)

![#70 D-20 M-1 Y-2023 W-Foxxive.jpg](https://github.com/user-attachments/assets/93857e4e-192a-48a3-a855-19198a30bce5)

![#71 D-27 M-1 Y-2023 W-@HostyTosty.jpg](https://github.com/user-attachments/assets/8349f229-ca51-46af-b785-e21c65a4b6d7)

![#72 D-3 M-2 Y-2023 W-Foxxive.jpg](https://github.com/user-attachments/assets/5865f9fc-ac82-465e-96cb-209582f2f338)

![#73 D-10 M-2 Y-2023 W-Leoart_s.jpg](https://github.com/user-attachments/assets/02aee67d-c0c4-45c2-aee5-52f3d4a360b5)

![#74 D-17 M-2 Y-2023 W-Aurora_sunset_arts.png](https://github.com/user-attachments/assets/a19cc92f-dfbc-4c48-aecf-c2c085e2118f)

![#75 D-24 M-2 Y-2023 W-Zukie.jpg](https://github.com/user-attachments/assets/65270e49-61ad-4477-a8d2-4938d9037ae3)

![#76 D-3 M-3 Y-2023 W-Zukie.jpg](https://github.com/user-attachments/assets/ed8ec02a-72d4-457f-b03c-a5f10355ad0f)

![#77 D-10 M-3 Y-2023 W-@Scoobis.jpg](https://github.com/user-attachments/assets/868ddfd4-2731-4b48-bff0-d85d13af0d98)

![#78 D-17 M-3 Y-2023 W-Zukie.png](https://github.com/user-attachments/assets/dcf27a9b-f65e-4088-ac03-3dd0421ee82f)

![#79 D-24 M-3 Y-2023 W-Cravy3781.png](https://github.com/user-attachments/assets/024b7c12-b3a7-423a-b319-af69edb505d9)

![#80 D-31 M-3 Y-2023 W-@sharfin_alpha3.jpg](https://github.com/user-attachments/assets/92773f2a-fc8a-46d3-9f77-2884cbd021c8)

![#81 D-7 M-4 Y-2023 W-Scoobis.jpg](https://github.com/user-attachments/assets/a0206240-243c-46b4-86c7-2c067ed619c2)

![#82 D-14 M-4 Y-2023 W-Bwa_artist.jpg](https://github.com/user-attachments/assets/58c99330-af6b-4d1f-b70f-35f43d60efd0)

![#83 D-21 M-4 Y-2023 W-Foxxive.jpg](https://github.com/user-attachments/assets/4d306223-29dd-43c5-9a9e-e10fe8f04c1e)

![#84 D-28 M-4 Y-2023 W-@Zeitzbach.jpg](https://github.com/user-attachments/assets/9e4a6e33-42c9-42fb-af29-bcb656f224b4)

![#85 D-5 M-5 Y-2023 W-Bluewolftail.jpg](https://github.com/user-attachments/assets/5684c1b5-c0ce-4e9d-9b73-6e01b1799c40)

![#86 D-12 M-5 Y-2023 W-CheepPlayz.jpg](https://github.com/user-attachments/assets/b30e4a17-9c24-4d34-b4fe-1355280124ff)

![#87 D-19 M-5 Y-2023 W-Zukie.jpg](https://github.com/user-attachments/assets/1d3a51a8-171f-4285-bd7b-b01ab2994ed4)

![#88 D-26 M-5 Y-2023 W-@BlueGut078.jpg](https://github.com/user-attachments/assets/d5ee4d38-eb43-463b-8426-32cae8f82506)

![#89 D-2 M-6 Y2023- W-3d_afernandez.png](https://github.com/user-attachments/assets/4129a5ad-00f9-4ec2-adee-b747e7e39d76)

![#90 D-9 M-6 Y-2023 W-Bwa_artist.jpg](https://github.com/user-attachments/assets/a5507ee2-907a-4c1f-a214-81d6476915c8)

![#91 D-16 M-6 Y-2023 W-@JeremasGuerra.jpg](https://github.com/user-attachments/assets/36b57adf-a3cf-42f9-b167-36fe45688b86)

![#92 D-23 M-5 Y-2023 W-@MAGNAYEChristi2.jpg](https://github.com/user-attachments/assets/62fb0a8b-9a66-439b-a257-cab1b7001f30)

![#93 D-30 M-6 Y-2023 W-Bluewolftail.jpg](https://github.com/user-attachments/assets/3f16504e-e054-4bfb-aaac-3a68f607be19)

![#94 D-7 M-7 Y-2023 W-@JingYi=JnagYi6.jpg](https://github.com/user-attachments/assets/e08756f7-6fe8-4a02-b8a8-d2db101fe707)

![#95 D-14 M-7 Y-2023 W-Duskdaminal.jpg](https://github.com/user-attachments/assets/509298be-c56d-4dd7-8c64-1099b34ba348)

![#96 D-21 M-7 Y-2023 W-@JingYi6=JangYi6.jpg](https://github.com/user-attachments/assets/13f3aba0-c215-468b-9079-6bf4b8cbafd4)

![#97 D-28 M-7 Y-2023 W-Le Norn Garner.jpg](https://github.com/user-attachments/assets/d788d0f6-ad5c-4795-8cf8-e43587b0260d)

![#98 D-4 M-8 Y-2023 W-Le Norn Garner.jpg](https://github.com/user-attachments/assets/81e5ed86-f4da-4a46-bc88-d0c42bbea6dd)

![#99 D-11 M-8 Y-2023 W-@JingYi6=JangYi6.jpg](https://github.com/user-attachments/assets/7ae9147b-22e7-4023-a1c9-a00c73f1eb82)

![#100 D-18 M-8 Y-2023 W-SharoSenpai.jpg](https://github.com/user-attachments/assets/8da50bd6-b99a-4156-b6de-3cfc39946870)

![#101 D-25 M-8 Y-2023 W-Bluewolftail.jpg](https://github.com/user-attachments/assets/9ca976eb-476c-4cff-ad5f-a01db2ed12bc)

![#102 D-1 M-9 Y-2023 W-RyokusenCrow.jpg](https://github.com/user-attachments/assets/674e042c-a626-4468-8ee9-8a9a06d9f091)

![#103 D-8 M-9 Y-2023 W-Zukie.jpg](https://github.com/user-attachments/assets/81c4b75a-aa6a-4cbc-9ce5-453507aacba0)

![#104 D-15 M-9 Y-2023 W-Foxxive.jpg](https://github.com/user-attachments/assets/5f4c17ad-31fc-49a4-9d17-d57368b106d5)

![#105 D-22 M-9 Y-2023 W-SlowSpeedrun.jpg](https://github.com/user-attachments/assets/a48b29bf-a648-45d5-9c35-c7ef4b18f28f)

![#106 D-29 M-9 Y-2023 W-FantasticClaws.jpg](https://github.com/user-attachments/assets/6f5b103e-5ffe-4eed-bc31-7cb4e3a75e06)

![#107 D-6 M-10 Y-2023 W-m3re_mail.jpg](https://github.com/user-attachments/assets/328764d3-c837-4322-92ee-641be882c757)

![#108 D-18 M-10 Y-2023 W-RyokusenCrow.jpg](https://github.com/user-attachments/assets/d9b60d29-fe75-40ae-807f-aec9e002d2c7)

![#109 D-20 M-10 Y-2023 W-lil_rekuro.jpg](https://github.com/user-attachments/assets/d29882b5-2f60-4517-8d75-9549c5620489)

![#110 D-27 M-10 Y-2023 W-SlowSpeedrun.jpg](https://github.com/user-attachments/assets/f1f96b27-9446-4e4b-8869-0f9000eebfe9)

![#111 D-3 M-11 Y-2023 W-SharoSenpai.jpg](https://github.com/user-attachments/assets/a69d4b7b-e06f-4d70-a354-34b963f646ac)

![#112 D-10 M-11 Y-2023 W-Johan3D.gif](https://github.com/user-attachments/assets/2c0ca10d-55da-4e33-ae11-db84ca936ebc)

![#113 D-17 M-11 Y-2023 W-Kotofe4ik08.jpg](https://github.com/user-attachments/assets/63cfbdee-1d95-4a77-8ea7-05d298708825)

![#114 D-24 M-11 Y-2023 W-SharoSenpai.jpg](https://github.com/user-attachments/assets/5ece9904-fca9-4db1-876c-da78f1eb48bf)

![#115 D-1 M-12 Y-2023 W-RyokusenCrow.jpg](https://github.com/user-attachments/assets/8c3e15e2-b249-4fb7-82a2-e5e7a0d53edf)

![#116 D-8 M-12 Y-2023 W-YetDarked.jpg](https://github.com/user-attachments/assets/bc5a9d90-b333-4c4c-818a-785e605f9689)

![#117 D-15 M-12 Y-2023 W-Johan3D.gif](https://github.com/user-attachments/assets/4c5211d9-f52d-4e11-b047-9a93cb5d42dc)

![#118 D-22 M-12 Y-2023 W-Bluewolftail.jpg](https://github.com/user-attachments/assets/44a3e58d-aba8-42a9-bb46-92dbbc8dbea3)

![#119 D-29 M-12 Y-2023 W-TheLucario452.jpg](https://github.com/user-attachments/assets/2f341bf5-110f-4566-bf96-b8fdb00f8994)

![#120 D-5 M-1 Y-2024 W-FantasticClaws.jpg](https://github.com/user-attachments/assets/8e852024-232f-4ba9-ba87-f1ada073c23a)

![#121 D-12 M-1 Y-2024 W-Kartes306.jpg](https://github.com/user-attachments/assets/13730025-15e9-4217-8faf-92278e7450b0)

![#122 D-19 M-1 Y-2024 W-Johan3D.gif](https://github.com/user-attachments/assets/c2a89ec9-e64a-4c88-88f3-ba8382979180)

![#123 D-26 M-1 Y-2024 W-Noobthemaster4th.jpg](https://github.com/user-attachments/assets/b714cb9b-6f1b-4661-bb66-7484493061c3)

![#124 D-2 M-2 Y-2024 W-MikaNorn.jpg](https://github.com/user-attachments/assets/fd595bb4-4504-41c2-9338-0ba3f4c4a029)

![#125 D-9 M-2 Y-2024 W-CheepPlayz.jpg](https://github.com/user-attachments/assets/a8152276-c333-4d6d-a122-903fa2cfd086)

![#126 D-16 M-2 Y-2024 W-Infimix.jpg](https://github.com/user-attachments/assets/12a1c0c3-e541-4109-9507-eba600d67bc0)

![#127 D-23 M-2 Y-2024 W-Glarefacer.jpg](https://github.com/user-attachments/assets/6abd7941-6d12-491b-961a-8710d15610c2)

![#128 D-1 M-3 Y-2024 W-BlagoRobot.jpg](https://github.com/user-attachments/assets/47343ab0-dfe0-4632-a85b-817394099dc9)

![#129 D-8 M-3 Y-2024 W-Infimix.jpg](https://github.com/user-attachments/assets/d3e2dab0-63de-4b02-8ced-f5fdb9d8fb7e)

![#130 D-15 M-3 Y-2024 W-Glarefacer.jpg](https://github.com/user-attachments/assets/0d79e840-2b54-4886-9732-613f2e9afe53)

![#131 D-22 M-3 Y-2024 W-The_wolft8998.gif](https://github.com/user-attachments/assets/015758db-1acf-42a3-a97b-96af555ced4a)

![#132 D-29 M-3 Y-2024 W-Infimix.jpg](https://github.com/user-attachments/assets/a2c54f5b-87ff-4bb3-b4ef-57add65b336d)

![#133 D-5 M-4 Y-2024 W-MikaNorn.jpg](https://github.com/user-attachments/assets/6a9b77a4-a639-4ede-b495-0483ead9db61)

![#134 D-12 M-4 Y-2024 W-Infimix.jpg](https://github.com/user-attachments/assets/9fef63f7-4459-494e-b49c-de7f72575aa0)

![#135 D-19 M-4 Y-2024 W-FantasticClaws.jpg](https://github.com/user-attachments/assets/c0d24b53-3625-4ff2-a0e8-8e588af66150)

![#136 D-26 M-4 Y-2024 W-The_wolft8998.gif](https://github.com/user-attachments/assets/dfae4d3a-f041-4252-a71a-404203003781)

![#137 D-3 M-5 Y-2023 W-ax.I_art.jpg](https://github.com/user-attachments/assets/4e03d476-9aaf-4949-b8a2-8ed21ec993e7)

![#138 D-10 M-5 Y-2024 W-Levie.jpg](https://github.com/user-attachments/assets/15d259e1-02e3-4a3a-95ac-8c5d26a42a50)

![#139 D-17 M-5 Y-2024 W-Infimix.jpg](https://github.com/user-attachments/assets/97aab1e0-cbb5-4575-a851-e0cd50f31adf)

![#140 D-24 M-5 Y-2024 W-BlagoRobot.jpg](https://github.com/user-attachments/assets/4db3f4ff-556a-4540-90bd-560a4360be5b)

![#141 D-31 M-5 Y-2024 W-The_wolft8998.jpg](https://github.com/user-attachments/assets/d24c54bd-0e9b-4d90-b683-9a28cae5340c)

![#142 D-7 M-6 Y-2024 W-Duque.jpg](https://github.com/user-attachments/assets/117f6614-07a1-418e-9676-138587e15758)

![#143 D-14 M-6 Y-2024 W-Duque.jpg](https://github.com/user-attachments/assets/34e53989-e9b1-4fda-a763-45d15a67ab61)

![#144 D-21 M-6 Y-2024 W-Josh Maus.jpg](https://github.com/user-attachments/assets/ca7c22ec-725d-4055-9ec2-fc0dfba2714f)

![#145 D-28 M-6 Y-2024 W-Duque.jpg](https://github.com/user-attachments/assets/b22dc613-4404-416e-af51-b608e5e32c30)

![#146 D-5 M-7 Y-2024 W-Josh Maus.jpg](https://github.com/user-attachments/assets/8082a2a9-769f-4f4d-81ff-9f5b531c5112)

![#147 D-12 M-7 Y-2024 W-Ari.jpg](https://github.com/user-attachments/assets/891ea516-7699-4041-bd21-8ebe9add83a4)

![#148 D-19 M-7 Y-2024 W-Duque.jpg](https://github.com/user-attachments/assets/9572e245-6bfb-4646-8e0f-e0ba3038cb19)

![#149 D-26 M-7 Y-2024 W-Levss170.jpg](https://github.com/user-attachments/assets/c0905f3d-c5a4-4790-b072-346ab65e9685)

![#150 D-2 M-8 Y-2024 W-Josh Maus.jpg](https://github.com/user-attachments/assets/ee47bb6e-4877-476d-805f-df86472927c6)

![#151 D-9 M-8 Y-2024 W-Duque.jpg](https://github.com/user-attachments/assets/0c33ba86-b6ce-41f7-8d5b-ff500d62cef2)

![#152 D-16 M-8 Y-2024 W-The_wolft8998.jpg](https://github.com/user-attachments/assets/b760abfd-876f-41fb-9e03-ae8cad2e56fc)

**Comment by Infimix2024** [comment]
@Valdi28 Hello! Here they are! Hope all these files work

**Comment by Valdi28** [comment]
Thank you, this facilitates this a lot 🙂
